name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Clona el repositorio
    - name: Clonar repositorio
      uses: actions/checkout@v3

    # Configura Python
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Cambia a la versión que necesites

    # Instala dependencias
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        
    # Ejecuta pruebas unitarias
    - name: Ejecutar pruebas
      run: |
        pytest tests/ # Cambia la ruta si es diferente
